"""add_project_content

Revision ID: 0ed5f4b2b7d7
Revises: 915382ca98f5
Create Date: 2026-04-14 17:02:27.680987

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '0ed5f4b2b7d7'
down_revision: Union[str, None] = '915382ca98f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
