"""add_project_content

Revision ID: 915382ca98f5
Revises: 0011_style_job_pause
Create Date: 2026-04-14 17:02:12.606310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '915382ca98f5'
down_revision: Union[str, None] = '0011_style_job_pause'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('content', sa.Text(), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'content')
    # ### end Alembic commands ###
