"""split project bible

Revision ID: ea8aaba06296
Revises: 0013_plot_skeleton_payload
Create Date: 2026-04-22 12:55:25.173005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea8aaba06296'
down_revision: Union[str, None] = '0013_plot_skeleton_payload'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_bibles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('inspiration', sa.Text(), nullable=False),
    sa.Column('world_building', sa.Text(), nullable=False),
    sa.Column('characters', sa.Text(), nullable=False),
    sa.Column('outline_master', sa.Text(), nullable=False),
    sa.Column('outline_detail', sa.Text(), nullable=False),
    sa.Column('runtime_state', sa.Text(), nullable=False),
    sa.Column('runtime_threads', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )

    # Copy data from projects to project_bibles
    connection = op.get_bind()
    import uuid
    import datetime

    projects = connection.execute(sa.text("""
        SELECT id, inspiration, world_building, characters,
               outline_master, outline_detail, runtime_state, runtime_threads,
               created_at, updated_at
        FROM projects
    """)).fetchall()

    for project in projects:
        connection.execute(
            sa.text("""
                INSERT INTO project_bibles (
                    id, project_id, inspiration, world_building, characters,
                    outline_master, outline_detail, runtime_state, runtime_threads,
                    created_at, updated_at
                ) VALUES (
                    :id, :project_id, :inspiration, :world_building, :characters,
                    :outline_master, :outline_detail, :runtime_state, :runtime_threads,
                    :created_at, :updated_at
                )
            """),
            {
                "id": uuid.uuid4().hex,
                "project_id": project[0],
                "inspiration": project[1],
                "world_building": project[2],
                "characters": project[3],
                "outline_master": project[4],
                "outline_detail": project[5],
                "runtime_state": project[6],
                "runtime_threads": project[7],
                "created_at": project[8],
                "updated_at": project[9],
            }
        )

    with op.batch_alter_table('projects') as batch_op:
        batch_op.drop_column('runtime_state')
        batch_op.drop_column('outline_detail')
        batch_op.drop_column('characters')
        batch_op.drop_column('world_building')
        batch_op.drop_column('outline_master')
        batch_op.drop_column('runtime_threads')
        batch_op.drop_column('inspiration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects') as batch_op:
        batch_op.add_column(sa.Column('inspiration', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('runtime_threads', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('outline_master', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('world_building', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('characters', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('outline_detail', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('runtime_state', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))

    op.execute("""
        UPDATE projects p
        SET inspiration = pb.inspiration,
            world_building = pb.world_building,
            characters = pb.characters,
            outline_master = pb.outline_master,
            outline_detail = pb.outline_detail,
            runtime_state = pb.runtime_state,
            runtime_threads = pb.runtime_threads
        FROM project_bibles pb
        WHERE p.id = pb.project_id
    """)

    op.drop_table('project_bibles')
    # ### end Alembic commands ###
